### ISSUE TITLE
Error in battery widget definition in rc.lua

### ISSUE THREAD

**Issue by Lv-291** [Strazil001/Dotfiles-AwesomeWM#3]
I noticed an issue in the definition of the battery widget in the rc.lua file of your repository. In the following line of code:
```lua
awful.widget.watch('bash -c "cat /sys/class/power_supply/BAT1/capacity"', 60, function(self, stdout)
```
the battery folder is specified as BAT1, but in my case, the battery folder is named BAT0, causing the widget to malfunction.

To solve this issue and ensure that the widget works for users with either BAT0 or BAT1 battery folder names, I propose the following code:
```lua
local battery_path = '/sys/class/power_supply/'

-- Find the battery folder that contains the "capacity" file
local battery_name
for dir in io.popen('ls -d ' .. battery_path .. '*'):lines() do
  if io.open(dir .. '/capacity') ~= nil then
    battery_name = dir:sub(#battery_path + 1)
    break
  end
end

if battery_name then
  local battery_capacity_command = 'cat ' .. battery_path .. battery_name .. '/capacity'

  -- Create the battery widget using the command found
  awful.widget.watch(battery_capacity_command, 60, function(widget, stdout)
    local capacity = tonumber(stdout)
    update_battery_widget(capacity)
  end)
else
  -- No battery folder was found
  print('No battery folder was found')
end
```
This code dynamically finds the correct battery folder to use for the widget, regardless of whether the folder is named BAT0 or BAT1.

**Comment by Strazil001** [comment]
Ty for pointing this out, will be fixed on the following commit.
